export const DEFAULT_VIDEOS = [
  {
    id: 1740215000000,
    title: 'Tree Pose Meditation',
    videoUrl: '/videos/tree.mp4',
    imageUrl: 'https://picsum.photos/seed/zen1/800/450',
    pose: 'Tree Pose',
    difficulty: 'Beginner',
    gender: 'Female',
    age: '30s',
    location: 'Zen Garden',
    speed: 'Slow',
    musicGenre: 'Ambient',
    prompt: 'Ambient music, Tree Pose, Beginner level, Female in 30s, Zen Garden setting, Slow pace'
  },
  {
    id: 1740214000000,
    title: 'Downward Dog Practice',
    videoUrl: '/videos/dog.mp4',
    imageUrl: 'https://picsum.photos/seed/zen2/800/450',
    pose: 'Downward Dog',
    difficulty: 'Intermediate',
    gender: 'Male',
    age: '40s',
    location: 'Temple',
    speed: 'Normal',
    musicGenre: 'Nature Sounds',
    prompt: 'Nature Sounds music, Downward Dog, Intermediate level, Male in 40s, Temple setting, Normal pace'
  },
  {
    id: 1740113760000,
    title: 'Morning Zen Session',
    videoUrl: '/videos/created_zen_1740113760000.mp4',
    imageUrl: 'https://picsum.photos/seed/zen3/800/450',
    pose: 'Lotus Position',
    difficulty: 'Beginner',
    gender: 'Female',
    age: '30s',
    location: 'Beach',
    speed: 'Slow',
    musicGenre: 'Piano',
    prompt: 'Piano music, Lotus Position, Beginner level, Female in 30s, Beach setting, Slow pace'
  },
  {
    id: 1771721003380,
    title: 'Evening Meditation',
    videoUrl: '/videos/zen_1771721003380.mp4',
    imageUrl: 'https://picsum.photos/seed/zen4/800/450',
    pose: 'Seiza',
    difficulty: 'Intermediate',
    gender: 'Male',
    age: '40s',
    location: 'Forest',
    speed: 'Normal',
    musicGenre: 'Ambient',
    prompt: 'Ambient music, Seiza, Intermediate level, Male in 40s, Forest setting, Normal pace'
  },
  {
    id: 1771724178156,
    title: 'Peaceful Practice',
    videoUrl: '/videos/zen_1771724178156.mp4',
    imageUrl: 'https://picsum.photos/seed/zen5/800/450',
    pose: 'Standing Zen',
    difficulty: 'Advanced',
    gender: 'Female',
    age: '50s',
    location: 'Mountain',
    speed: 'Fast',
    musicGenre: 'Flute',
    prompt: 'Flute music, Standing Zen, Advanced level, Female in 50s, Mountain setting, Fast pace'
  },
  {
    id: 1771730922925,
    title: 'Deep Relaxation',
    videoUrl: '/videos/zen_1771730922925.mp4',
    imageUrl: 'https://picsum.photos/seed/zen6/800/450',
    pose: 'Walking Meditation',
    difficulty: 'Beginner',
    gender: 'Male',
    age: '20s',
    location: 'Temple',
    speed: 'Slow',
    musicGenre: 'Nature Sounds',
    prompt: 'Nature Sounds music, Walking Meditation, Beginner level, Male in 20s, Temple setting, Slow pace'
  },
  {
    id: 1771731422783,
    title: 'Mindful Movement',
    videoUrl: '/videos/zen_1771731422783.mp4',
    imageUrl: 'https://picsum.photos/seed/zen7/800/450',
    pose: 'Lying Down',
    difficulty: 'Intermediate',
    gender: 'Female',
    age: '30s',
    location: 'Zen Garden',
    speed: 'Normal',
    musicGenre: 'Ambient',
    prompt: 'Ambient music, Lying Down, Intermediate level, Female in 30s, Zen Garden setting, Normal pace'
  },
  {
    id: 1771731754761,
    title: 'Tranquil Session',
    videoUrl: '/videos/zen_1771731754761.mp4',
    imageUrl: 'https://picsum.photos/seed/zen8/800/450',
    pose: 'Lying Down',
    difficulty: 'Advanced',
    gender: 'Female',
    age: '60s+',
    location: 'Temple',
    speed: 'Fast',
    musicGenre: 'Silence',
    prompt: 'Silence music, Lying Down, Advanced level, Female in 60s+, Temple setting, Fast pace'
  },
  {
    id: 1771733852130,
    title: 'Harmony Practice',
    videoUrl: '/videos/zen_1771733852130.mp4',
    imageUrl: 'https://picsum.photos/seed/zen9/800/450',
    pose: 'Seiza',
    difficulty: 'Beginner',
    gender: 'Female',
    age: '40s',
    location: 'Forest',
    speed: 'Normal',
    musicGenre: 'Flute',
    prompt: 'Flute music, Seiza, Beginner level, Female in 40s, Forest setting, Normal pace'
  }
]
